### ISSUE TITLE
Preload shape collections as an option

### ISSUE THREAD

**Issue by larvanitis** [evolus/pencil#124]
There should be an option in the program Settings, which makes the loading of shapes in the collections instant, ie. not _while you scroll_.

As it is right now, it is kind of a pain in the ass to locate an icon in large collections like _Material Icons_. You have to scroll, wait for shapes to render, check, scroll again, wait... etc.

* Operating system: Linux
* Pencil version: 3.0.0-rc.1

**Comment by brainscript** [comment]
**+1** I'd like to see that too.

**Comment by pnvananh** [comment]
Instant loading of collection may cause the underlying Electron to crash. The lazy loading of shape icons was introduce to prevent this crashing.

A small enhancement was added to load the icon a little bit ahead of the scrolling so that scrolling at a normal speed won't give the users an impression that icons are lazily loaded.
