### ISSUE TITLE
How can I execute Pencil through a desktop shorcut?

### ISSUE THREAD

**Issue by douglas-melo** [evolus/pencil#517]
* Operating system: CentOS 7.5
* Pencil version: 3.0.4

Hello.

I'm new on `nodejs` and `electron` desktop's applications.

Does anyone know how can I make a `.desktop` file to run Pencil?

I mean, like a regular linux shortcut to run it without to need navigate to the pencil dir, and execute `npm start` through the terminal all the time when I want use it.

Is it possible?

Thanks!

**Comment by rustyhamsterr** [comment]
Hey there, this is not an issue with pencil,
but a question for a linux forum of your choice or stackoverflow.

Anyway I would create a shellscript and put
`cd path/to/pencil`
`npm start`
inside.

you can put this script anywhere you want and create a shortcut to this script.

Next time: general questions -> StackOverflow or better a large linux/distrospecific forum :stuck_out_tongue:

**Comment by douglas-melo** [comment]
Hey, thanks for your response.

I agree, that's not a necessarily a pencil issue, but it doesn't a linux question too, by the way why it would be?

I tried something like your suggestion before posting, it didn't work, today I found out it was because there wasn't any prefix to `npm` do that. 

So, without a `npm --prefix` your script only'd work in the same directory, and it wouldn't work from anywhere with or without prefix like a linux shortcut, because that's not in `/usr/local/bin` or `/usr/bin`(linux question?) :stuck_out_tongue:

https://docs.npmjs.com/misc/config#prefix

I have solved my issue with this script in `usr/local/bin` I can call it from anywhere, and make a desktop shortcut.

```
#!/bin/bash
nohup npm start --prefix /path-to/pencil ./node_modules/.bin/electron > /dev/null 2>&1 &
```

See ya.

**Comment by rustyhamsterr** [comment]
I agree that this is the more elegant way and glad you solved this.
It does work by changing the directory within the shellscript, as the shells working directory is your pencil folder afterwards, you are able to run npm without a folder prefix.
But as I said: Your prefix solution looks much cleaner.

I considered this a linux question, because it is about desktop shortcuts and linking terminal applications, that require a defined working directory(, in linux environment)).

Cya 😄
